### ISSUE TITLE
Please stop opening wrong PRs from a bot.

### ISSUE THREAD

**Issue by leobalter** [adius/feram#1]
Opening a PR with wrong changes is ok if done manually, as it implies a good will to improve something.

Having a bot to open PRs in random projects with dull changes is not ok.

**Comment by adius** [comment]
I'd say it exactly the other way round =D

…and this was the first pull request which was wrong.
I also removed the typo fix now. It's too ambiguous.
The next version of feram will check for the target language ;-)

But why are you so hostile towards bots? They have feelings too, you know ;-)

**Comment by leobalter** [comment]
I'm not hostile, I'm +1 to open source contributions. I'm only asking you to avoid unnecessary noise on many projects. It happened only on a single project I receive notifications, but your bot suggested I could give a feedback here.

**Comment by adius** [comment]
>  I'm only asking you to avoid unnecessary noise
I'll definitely try, but I can't guarantee that the a few stupid ones will slip through. 😕
Thanks for your feedback anyways! I hope the next pull request will be a good one 😉

**Comment by adius** [comment]
Btw: Feram is not going crazy anymore
He creates just a list of possible fixes and then I give a yes or no.
This should massively reduce noise =P

**Comment by leobalter** [comment]
That's great! Thanks!
