### ISSUE TITLE
Don't attempt to fix typos in sourcemap (.map) files

### ISSUE THREAD

**Issue by cvrebert** [adius/feram#2]
Refs https://github.com/twbs/bootstrap/pull/19741/commits/3fb6a9c1e6d61ecf18a07857e5b3cd1323ad2a53
Background: http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

**Comment by adius** [comment]
Fixed in 2aef5eee2a008eb523e535c172c7d4f39f014e0a
